/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* src = "parameterized_seq_detector.v:1.1-26.10" *)
module parameterized_seq_detector(clk, rst, serial_in_bit, detected);
  (* src = "parameterized_seq_detector.v:19.13-19.62" *)
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "parameterized_seq_detector.v:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "parameterized_seq_detector.v:8.16-8.24" *)
  output detected;
  reg detected;
  (* src = "parameterized_seq_detector.v:6.11-6.14" *)
  input rst;
  wire rst;
  (* src = "parameterized_seq_detector.v:7.11-7.24" *)
  input serial_in_bit;
  wire serial_in_bit;
  reg [2:0] shift_reg;
  assign _1_ = shift_reg[0] & ~(serial_in_bit);
  assign _2_ = shift_reg[1] | ~(shift_reg[2]);
  assign _0_ = _1_ & ~(_2_);
  (* src = "parameterized_seq_detector.v:13.1-24.4" *)
  always @(posedge clk)
    if (!rst) shift_reg[0] <= 1'h0;
    else shift_reg[0] <= serial_in_bit;
  (* src = "parameterized_seq_detector.v:13.1-24.4" *)
  always @(posedge clk)
    if (!rst) shift_reg[1] <= 1'h0;
    else shift_reg[1] <= shift_reg[0];
  (* src = "parameterized_seq_detector.v:13.1-24.4" *)
  always @(posedge clk)
    if (!rst) shift_reg[2] <= 1'h0;
    else shift_reg[2] <= shift_reg[1];
  (* src = "parameterized_seq_detector.v:13.1-24.4" *)
  always @(posedge clk)
    if (!rst) detected <= 1'h0;
    else detected <= _0_;
endmodule
